name = "ConstrainedSystems.jl"
uuid = "c257ce95-4918-4279-a47c-50fdbcb74a04"
authors = ["Jeff Eldredge <jdeldre@g.ucla.edu>"]
repo = "https://github.com/JuliaIBPM/ConstrainedSystems.jl.git"
version = "0.1.0"
